### ISSUE TITLE
Epic - Branding and Presentation

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#1]
### Description

- [ ]  User Story: As a gym owner, I want the website to have a unique and appealing design so that visitors can distinguish Tough glove from other boxing gyms.
- [ ]  User Story: As a potential member, I want to see a clear mission or vision statement from Tough glove, so I can understand its value proposition and what makes it different.
- [ ] User Story: As a potential member, I want to see testimonials from other members, so I can trust the quality of the training.
