### ISSUE TITLE
User Story: 

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#10]
## Epic: #2 

>  As a member, I want to create an account so I can book classes and manage my bookings.

## Estimation of Effort

- 3 Story Points

## End User Goal:

- Create a new account to be able to book classes and manage bookings

## End Business Goal:
---
- Enable users to create accounts to manage their classes

## Acceptance Criteria:
---
- User must provide all relevant basic information in being able make a booking. (Name, Phone, Email)
- User should be able to login and log out once their account is created
- User should have the ability to access a profile page that shows their account overview
- User should have the ability to delete account

## Tasks:
---
* [ ] Create backend profile logic (create backend)
* [ ] Add style and navigation to front end ( create functionality with HTML and CSS)
* [ ] Add icons if necessary for ease of use (Style to suit web theme)
