### ISSUE TITLE
User Story: User Logins

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#11]
## Epic: #2 

> As a member, I want to be able to log in and out of my account, so I can securely access my personal information and bookings.

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Log in and out of the website

## End Business Goal:
---
- Provide members a way to get in and out of their accounts 

## Acceptance Criteria:
---
- User can log in to their account through the website and instantly access all of their booking and profile information
- User can log out of their account and be redirected to the home page

## Tasks:
---
* [ ] Redirect to account when a member creates their account
* [ ] Redirect to the home page when a member logs out of their account
* [ ] Implement unit tests to check for member logins and logouts
