### ISSUE TITLE
User Story: Class Calendar

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#13]
## Epic: #12 

> As a member, I want to see a calendar or schedule of available classes, so I can choose when to attend.

## Estimation of Effort

3 Story Points

## End User Goal:
---
- See class schedules 

## End Business Goal:
---
- Advertise available classes

## Acceptance Criteria:
---
- User can see on a calendar what classes are available

## Tasks:
---
* [ ] Design calendar view within the user accounts
* [ ] Populate the calendar with group classes created in the database by the admin
* [ ] Populate the calendar with 1:1 classes created in the database by the admin
