### ISSUE TITLE
User Story: Admin Boxing Class Creation

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#14]
## Epic: #12 

> As the gym owner, I want to create classes that members can attend so that I can manage by timetable.

## Estimation of Effort

2 Story Points

## End User Goal:
---
- Create different class types in the calendar to manage the gym timetable

## End Business Goal:
---
- Create different class types in the calendar

## Acceptance Criteria:
---
- The owner can create 1:1 classes with only 1 attendee
- The owner can create group classes with up to 30 attendees
- Classes will not be created if there are conflicting timetables

## Tasks:
---
* [x] Create DB model of the classes
* [x] Create a group form for creating classes
* [x] Create a 1:1 form for creating classes
* [x] Ensure form validation prevents conflicting classes being made
* [x] Write unit tests for creating the classes
