### ISSUE TITLE
User Story: Class Management By Admin

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#15]
## Epic: #12 

> As a gym owner, I want to update and delete my classes so that I can update them if there are any changes of plans.

## Estimation of Effort

2 Story Points

## End User Goal:
---
- Update and Delete Classes

## End Business Goal:
---
- Ensure classes can be adjusted to allow changes of plans and avoid confusion with gym members

## Acceptance Criteria:
---
- Admin can update classes in their account with an update form
- Admin can delete classes in their account with a delete form
- When an admin updates classes, form validation ensures that there are no conflicts occurring between classes

## Tasks:
---
* [ ] Create class update form for each class
* [ ] Create class deletion form for each class
* [ ] Position update and delete forms next to each class in the admin account
* [ ] Ensure form validation prevents admin from creating overlapping classes
