### ISSUE TITLE
User Story: Member Class Booking

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#16]
## Epic: #12 

>  As a member, I want to book 1:1 / group classes so I can get personalized/group training.

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Book a class for a specific time and date

## End Business Goal:
---
- Receive booking from gym members

## Acceptance Criteria:
---
- Member can book 1:1 and group classes
- Members can no longer book a class if they are full
- Members can edit their classes and remove themselves if they wish

## Tasks:
---
* [ ] Create group class booking form
* [ ] Create 1:1 class booking form
* [ ] Create class editing form 
* [ ] Link buttons to each form for each user
