### ISSUE TITLE
User Story: Blog Pages

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#19]
## Epic: #17 

> As a potential member, I want to read articles or blog posts about boxing techniques, fitness tips, and gym updates, so I can see the expertise of the gym and stay engaged..

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Consume blog content

## End Business Goal:
---
- Rank on keywords and acquire more users

## Acceptance Criteria:
---
- Blog home page shows all posts
- Each post opens up to the relevant article 
- Users can leave comments on the articles

## Tasks:
---
* [ ] Read blog content from db and present it on the blog home page
* [ ] Present each individual article that the user clicks on
* [ ] Enable readers to comment on blog posts
