### ISSUE TITLE
User Story: 

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#5]
## Epic: 

> As a gym owner, I want the website to have a unique and appealing design so that visitors can distinguish Tough Glove from other boxing gyms.

## Estimation of Effort

3 Story Points

## End User Goal:
---
- Distinguish tough glove branding from competitors

## End Business Goal:
---
- Enable tough glove to be identified from the competition

## Acceptance Criteria:
---
- Tough glove can be identified through it's branding (colours, typography, logos and messaging)

## Tasks:
---
* [ ] Create Header and Footer template designs in HTML and CSS using django templating language
* [ ] Implement key colour and typography decisions in style.css
* [ ] Ensure website design is responsive on all tablet and mobile sizes
