### ISSUE TITLE
User Story: Testimonials

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#6]
## Epic #1 : 

> As a potential member, I want to see testimonials from other members, so I can trust the quality of the training.

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Examine testimonial cards

## End Business Goal:
---
- Display social proof to potential users to increase conversion rate

## Acceptance Criteria:
---
- 2 Testimonials displayed on the website from existing members 

## Tasks:
---
* [ ] Create testimonial cards and design
* [ ] Ensure testimonials are responsive
* [ ] Populate testimonials with content
