### ISSUE TITLE
User Story: Calls To Action

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#7]
## Epic: #1 

> As a potential member, I want to see a clear call to action to join the gym, so I know the next steps to take.

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Clear call to action to join the gym

## End Business Goal:
---
- Increase conversion rates by reducing friction for potential members to sign up

## Acceptance Criteria:
---
- 3 calls to action on the home page
- All calls to action redirect to contact forms or signup forms 

## Tasks:
---
* [x] Implement styling for calls to action
* [x] Add 3 call to action buttons - 1 for member signup, 1 for contact us
* [x] Implement unit tests for all buttons
