### ISSUE TITLE
User Story: Class Types

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#8]
## Epic: #1 

> As a potential member, I want to know about the different types of classes and their objectives (e.g., fitness vs. boxing principles), so I can choose the right class for me.

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Evaluate the different signup classes

## End Business Goal:
---
- Educate potential members on the different classes available

## Acceptance Criteria:
---
- 2 class types presented as cards on homepage

## Tasks:
---
* [x] Create class cards
* [x] Ensure both classes redirect to a signup page or log a user in 
* [x] Unit tests for both classes
