### ISSUE TITLE
User Story: Trainer Cards

### ISSUE THREAD

**Issue by BOM-98** [BOM-98/tough-glove-project-4#9]
## Epic: #1 

> As a potential member, I want to see the profiles of the trainers or coaches, so I can trust their expertise..

## Estimation of Effort

- 2 Story Points

## End User Goal:
---
- Evaluate the gym coaches

## End Business Goal:
---
- Display the authority of the coaches on the site

## Acceptance Criteria:
---
- one card displayed for each coach on the homepage

## Tasks:
---
* [ ] Design the home cards 
* [ ] Ensure cards are responsive on the website
* [ ] Implement the cards with web-optimized images
